name: Releaser

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: ./
        with:
          changelog: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Attach Files
      #   uses: stacksjs/action-releaser@v1
      #   with:
      #     files: |
      #       bin/bin-name-linux-x64
      #       bin/bin-name-linux-arm64
      #       bin/bin-name-windows-x64.exe
      #       bin/bin-name-darwin-x64
      #       bin/bin-name-darwin-arm64
